## Summary

- Analyzed 999 Google Reviews across Minimalix, Livspace, and HomeLane.
- Processed 546 text reviews using NLP techniques.
- Identified major satisfaction drivers and complaint themes.
- Found that dissatisfied customers write 2.6x longer reviews.
- HomeLane complaints focus on execution and delays.
- Livspace complaints focus on post-sales service.
- Minimalix complaints focus on lead quality and subscription ROI.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
plt.style.use('ggplot')
from google.colab import files

### Data Collection & Performing EDA

In [ ]:
#importing the data from Github
url = 'https://raw.githubusercontent.com/TusharIITg01/voice-of-customer-analytics/main/Company%20Reviews%20%20-%20Sheet1.csv'
df = pd.read_csv(url, encoding= 'unicode_escape')

In [ ]:
df

,Company,rating,reviewer,review_text
0,Minimalix,1,Hardik Ojha,I had a very disappointing experience with Min...
1,Minimalix,5,Vipin Pal,"Recently I subscribed PLP Pro Plus, out of 6 l..."
2,Minimalix,5,Johnsan Barla,As per my overall experience Minimalix is one ...
3,Minimalix,5,The Design Studiokl,1/5\n \n My experience with Minimalix has been...
4,Minimalix,1,Supriya Vimal,"Very BadMost of the leads were either invalid,..."
...,...,...,...,...
994,HomeLane,5,Monu Khan,NaN
995,HomeLane,5,Yadav Madhubala,NaN
996,HomeLane,5,Amrit 2,NaN
997,HomeLane,5,Anish yadav,NaN
998,HomeLane,5,Md Sazzad,NaN

In [ ]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      999 non-null    object
 1   rating       999 non-null    int64
 2   reviewer     999 non-null    object
 3   review_text  546 non-null    object
dtypes: int64(1), object(3)
memory usage: 31.3+ KB

(999, 4)

In [ ]:
df.isnull().sum()

Company          0
rating           0
reviewer         0
review_text    453
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(3)

In [ ]:
df["Company"].value_counts()

Company
Livspace     350
HomeLane     332
Minimalix    317
Name: count, dtype: int64

In [ ]:
df["rating"].describe()

count    999.000000
mean       4.456456
std        1.283413
min        1.000000
25%        5.000000
50%        5.000000
75%        5.000000
max        5.000000
Name: rating, dtype: float64

In [ ]:
df["rating"].value_counts().sort_index()

rating
1    112
2      5
3     11
4     58
5    813
Name: count, dtype: int64

In [ ]:
df.groupby("Company")["rating"].mean()

Company
HomeLane     4.397590
Livspace     4.711429
Minimalix    4.236593
Name: rating, dtype: float64

Total reviews me se kitto me text review likha h

In [ ]:
df.groupby("Company")["review_text"].apply(
    lambda x: x.notna().sum()
)

Company
HomeLane     217
Livspace     129
Minimalix    200
Name: review_text, dtype: int64

Only 54.6% of reviews contain textual feedback
Livspace has the lowest proportion of text reviews despite having the highest rating.

In [ ]:
text_df = df[
    df["review_text"].notna()
].copy()

In [ ]:
text_df.shape

(546, 4)

In [ ]:
text_df["review_length"] = (
    text_df["review_text"]
    .astype(str)
    .apply(len)
)

In [ ]:
text_df.groupby("rating")[
    "review_length"
].mean()

rating
1    441.792208
2    310.333333
3    157.375000
4    174.756098
5    168.880096
Name: review_length, dtype: float64

Customers who have a poor experience provide significantly more detailed feedback than satisfied customers.

This suggests that dissatisfied customers are more motivated to explain issues, making negative reviews a rich source of operational insights.

Rating	Avg Review Length
1⭐	442 chars
2⭐	310 chars
3⭐	157 chars
4⭐	175 chars
5⭐	169 chars

In [ ]:
text_df["review_length"].describe()

count     546.000000
mean      208.417582
std       330.583995
min         4.000000
25%        48.000000
50%       111.500000
75%       222.000000
max      3810.000000
Name: review_length, dtype: float64

In [ ]:
text_df.nlargest(
    5,
    "review_length"
)[["Company","rating","review_length"]]

      Company  rating  review_length
392  Livspace       5           3810
753  HomeLane       1           2932
835  HomeLane       5           1766
365  Livspace       1           1752
674  HomeLane       1           1609

## Text Preprocessing

In [ ]:
!pip install -q spacy
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 74.3 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import re
import spacy
import pandas as pd

nlp = spacy.load("en_core_web_sm")

In [ ]:
def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
text_df["clean_text"] = (
    text_df["review_text"]
    .apply(clean_text)
)

## Lemmatization

In [ ]:
def lemmatize(text):

    doc = nlp(text)

    return " ".join(
        token.lemma_
        for token in doc
        if not token.is_stop
        and not token.is_punct
        and len(token.text) > 2
    )

In [ ]:
text_df["processed_text"] = (
    text_df["clean_text"]
    .apply(lemmatize)
)

In [ ]:
text_df[
    [
        "review_text",
        "processed_text"
    ]
].head()

,review_text,processed_text
0,I had a very disappointing experience with Min...,disappointing experience minimalics official j...
1,"Recently I subscribed PLP Pro Plus, out of 6 l...",recently subscribe plp pro plus lead visit con...
2,As per my overall experience Minimalix is one ...,overall experience minimalix good company term...
3,1/5\n \n My experience with Minimalix has been...,experience minimalix extremely disappointing s...
4,"Very BadMost of the leads were either invalid,...",badmost lead invalid badinterested enquiry fee...

In [ ]:
text_df.to_csv(
    "reviews_processed.csv",
    index=False
)

In [ ]:
text_df[
["review_text","processed_text"]
].head(10)

,review_text,processed_text
0,I had a very disappointing experience with Min...,disappointing experience minimalics official j...
1,"Recently I subscribed PLP Pro Plus, out of 6 l...",recently subscribe plp pro plus lead visit con...
2,As per my overall experience Minimalix is one ...,overall experience minimalix good company term...
3,1/5\n \n My experience with Minimalix has been...,experience minimalix extremely disappointing s...
4,"Very BadMost of the leads were either invalid,...",badmost lead invalid badinterested enquiry fee...
5,Excellent experience with minimalix based upon...,excellent experience minimalix base initial co...
6,They provide exceptional leads and engage in e...,provide exceptional lead engage effective comm...
8,I had a very good experience working with Mini...,good experience work minimalix genuinely helpf...
9,Good company with excellent customer service,good company excellent customer service
10,Extremely poor service. The leads shared were ...,extremely poor service lead share interested c...

In [ ]:
text_df[text_df["Company"] == "Minimalix"][
    ["review_text"]
].sample(20, random_state=42)

                                           review_text
109  Main apki service se bahut impressed hun. Apki...
17   One of the best company in interior design indust
33   I've using Minimalix leads services since 2023...
193               Very bed company aur 3rd grade owner
153                           Value for money services
134  They have given us very good work, their team ...
76   Minimalix is fantastic company, Their pre-qual...
210          Satisfied with Minimalix's interior work.
215  One of the best company for interior design se...
49   This company runs on fake promises. They talk ...
73   Feeling wow! Minimalix is exceptional company ...
237  I got know about Minimalix through word of mou...
202                      Fully supportive organization
88      Good company and polite customer support team.
254  I got experience more than expected.\n Entire ...
219  I must mention that minimalix team are very pr...
62   Not reliable.\n Leads dont respond\n Then they...
184  PLP Pro is world class product snd excellent c...
92     Unbelievable customer support. Highly recommend
75   I have had a very good experience with Minimal...

In [ ]:
partner_keywords = [
    "lead",
    "client",
    "subscription",
    "plp",
    "reno",
    "marketing",
    "sales",
    "conversion",
    "enquiry"
]

customer_keywords = [
    "design",
    "interior",
    "home",
    "kitchen",
    "wardrobe",
    "execution",
    "project",
    "designer",
    "installation"
]

In [ ]:
def classify_review(text):

    text = str(text).lower()

    partner_score = sum(
        word in text
        for word in partner_keywords
    )

    customer_score = sum(
        word in text
        for word in customer_keywords
    )

    if partner_score > customer_score:
        return "Partner"

    elif customer_score > partner_score:
        return "Customer"

    else:
        return "General"

In [ ]:
text_df["segment"] = (
    text_df["review_text"]
    .apply(classify_review)
)

## **Customer Behavior Analysis**
General reviews - 267 | Customer reviews - 229 | Partner reviews - 50
Segmentation seems off

In [ ]:
text_df["segment"].value_counts()

segment
General     267
Customer    229
Partner      50
Name: count, dtype: int64

In [ ]:
text_df[text_df["segment"]=="General"][
    ["Company","review_text"]
].sample(20, random_state=42)

       Company                                        review_text
169  Minimalix      Good service, go with 10K packages always....
101  Minimalix                     Nice company , full supportive
563   Livspace                      Good experience with livspace
791   HomeLane                                           Gangsara
548   Livspace       Good service, but regular occurring problem.
719   HomeLane                                               Nice
129  Minimalix  Good company. Prompt responses from customer s...
931   HomeLane  Hi Homelane is worse company to have a deal wi...
611   Livspace  Thankyou for the quick response. Person was he...
286  Minimalix     Minimliks ek good compny wiswas ke layak hai .
607   Livspace              It's a great session with Ms Sandhya.
330   Livspace  Donât take there service, they are unprofess...
911   HomeLane    Overall a great experience.detailed explanation
276  Minimalix  100% satisfied hun iss company se...team bhi k...
550   Livspace  This company make my furniture worst.\n No qua...
212  Minimalix  Not promissing as they talked and approached f...
463   Livspace         Great experience , polite and helpful team
420   Livspace                                     Excellent work
795   HomeLane                                 Very good and nice
24   Minimalix  Great company in terms of customer support and...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [ ]:
def top_words(company):

    temp = text_df[text_df["Company"] == company]

    vec = CountVectorizer(
        stop_words="english",
        max_features=30
    )

    X = vec.fit_transform(
        temp["processed_text"]
    )

    freq = X.toarray().sum(axis=0)

    words = vec.get_feature_names_out()

    return (
        pd.DataFrame({
            "word": words,
            "freq": freq
        })
        .sort_values(
            "freq",
            ascending=False
        )
    )

In [ ]:
top_words("Minimalix").head(20)

            word  freq
12     minimalix    84
22       service    75
1        company    74
8           good    73
11          lead    70
2       customer    66
10      interior    55
23       support    52
4         design    51
25          team    44
13         money    43
20     recommend    40
7     experience    37
9         highly    35
6      excellent    33
16  professional    26
15           pro    25
19       quality    21
14           plp    21
28          work    20

In [ ]:
top_words("HomeLane").head(20)

          word  freq
14    homelane   147
4       design   107
7   experience    94
26        team    90
29        work    87
22     project    71
9         good    55
13        home    54
5     designer    48
15    interior    48
17        like    43
25     service    40
28        time    38
10       great    38
27       thank    35
18        look    30
24   recommend    30
21     process    30
11        help    28
20     overall    27

In [ ]:
top_words("Livspace").head(20)

          word  freq
29        work    47
7         good    46
26        team    39
25     service    37
18    livspace    35
6   experience    32
22     project    25
8        great    17
27       thank    17
24        sale    17
15         job    16
21        post    15
19       month    14
4       design    14
23     quality    14
9         home    13
3     complete    13
10      instal    13
2      company    10
0      almirah    10

## Negative Review Analysis

In [ ]:
negative_df = text_df[text_df["rating"] <= 2]

In [ ]:
negative_df.sample(5)

,Company,rating,reviewer,review_text,review_length,clean_text,processed_text,segment
194,Minimalix,1,Zaid,Ye company ek dam frood hai paise leke fir cal...,216,ye company ek dam frood hai paise leke fir cal...,company dam frood hai paise leke fir bhi nahi ...,General
707,HomeLane,1,Anurag,I booked interior services with homelane aroun...,1157,i booked interior services with homelane aroun...,book interior service homelane mar start discu...,Customer
205,Minimalix,1,Hardik Kaul,Please be careful before choosing to go ahead ...,277,please be careful before choosing to go ahead ...,careful choose ahead hard earn money bad revie...,General
679,HomeLane,1,Rahul Bharadia,"False commitment on timeline, poor budget esti...",953,false commitment on timeline poor budget estim...,false commitment timeline poor budget estimate...,Customer
365,Livspace,1,Devender Arora,A cautionary account for anyone considering Li...,1752,a cautionary account for anyone considering li...,cautionary account consider livspace home inte...,Customer

In [ ]:
negative_df["Company"].value_counts()

Company
HomeLane     30
Minimalix    29
Livspace     21
Name: count, dtype: int64

In [ ]:
negative_df[
    ["Company","review_text"]
].sample(20, random_state=42)

       Company                                        review_text
330   Livspace  Donât take there service, they are unprofess...
0    Minimalix  I had a very disappointing experience with Min...
193  Minimalix               Very bed company aur 3rd grade owner
331   Livspace  I paid premium so that educated, experienced t...
168  Minimalix  Ek dum fraud company. Paise lene k baad respon...
228  Minimalix                           Worst company of my life
55   Minimalix  You trust , when some one makes a commitment a...
919   HomeLane  Loving how my bedroom interiors turned out. Th...
15   Minimalix  Thank you for your response. However, my revie...
72   Minimalix  Title: Poor Value for Money with PLP Pro\n Rev...
619   Livspace  inspite of paying advance upfront, didnât ge...
361   Livspace  Livespace is a fraud company they provide infl...
829   HomeLane  Opted HomeLane for home interiors. Good experi...
373   Livspace  CAUTION\n \n Unchi dukan phika pakwaan,,,,this...
839   HomeLane  Homelane designed a custom wardrobe for my bed...
551   Livspace  I wish I could give negative rating to Livspac...
931   HomeLane  Hi Homelane is worse company to have a deal wi...
760   HomeLane  They don't provide customisation as per client...
711   HomeLane  I availed their services and, unfortunately, e...
481   Livspace  I ordered from them 2 chairs on 3rd of March.....

| Root Cause  MINIMALIX        | Confidence |
| ---------------------------- | ---------- |  
| Lead Quality Issues          | High       |
| Subscription Value Issues    | High       |
| Post-payment Support         | High       |
| Trust / Credibility Concerns | Medium     |


| Root Cause  HomeLane      | Confidence |
| ------------------------- | ---------- |
| Customization Limitations | High       |
| Service Experience        | High       |
| Project Execution         | Medium     |
| Customer Communication    | Medium     |

| Root Cause Livspace          | Confidence |
| ---------------------------- | ---------- |
| Premium Pricing vs Value Gap | High       |
| Post-Sales Support           | High       |
| Service Quality              | Medium     |
| Expectation Mismatch         | High       |

In [ ]:
negative_df = text_df[text_df["rating"] <= 2].copy()

In [ ]:

def top_negative_words(company):

    temp = negative_df[
        negative_df["Company"] == company
    ]

    vec = CountVectorizer(
        stop_words="english",
        max_features=50
    )

    X = vec.fit_transform(
        temp["processed_text"]
    )

    freq = X.toarray().sum(axis=0)

    return (
        pd.DataFrame({
            "word": vec.get_feature_names_out(),
            "freq": freq
        })
        .sort_values(
            "freq",
            ascending=False
        )
    )

## Root Cause Analysis

In [ ]:
top_negative_words("Minimalix").head(20)

          word  freq
22        lead    30
24       money    20
9      company    14
42     service    10
16  experience    10
23   minimalix     8
15         don     7
45        time     7
18       fraud     7
10    complete     6
29        poor     6
32     provide     6
13    customer     6
4          bad     6
40    response     6
49       waste     5
36      refund     5
43       share     5
19         hai     5
41      review     5

RCA

1.  ROI on subscription
2.  Post-payment support
3. Lead quality

In [ ]:
top_negative_words("HomeLane").head(20)

          word  freq
18    homelane    38
9       design    24
32     project    22
41        team    22
49        work    19
39     service    14
14  experience    14
10    designer    13
25       month    11
12         don    10
21        like    10
27         pay    10
38         say    10
45        time     9
4      company     8
44       thing     8
15        good     8
3         come     8
33     promise     8
36      refund     8

RCA

1.  Project execution
2.  Timeline management
3. Delivery commitments

This is classic operations-management pain.

In [ ]:
top_negative_words("Livspace").head(20)

              word  freq
48            work    19
41            team    13
34         project    12
2              bad     9
14             don     8
27        livspace     8
30           month     8
6          company     8
39         service     7
17      experience     7
32             pay     7
25            like     7
7         complete     6
12          design     6
29           money     6
38            sale     6
28            look     6
4            brand     5
47           waste     5
44  unprofessional     5

RCA

1.  Service experience
2.  Post sales interaction
3. Value received

# ***Angry customers write 2.6x longer reviews***

In [ ]:
negative_df.nlargest(
    10,
    "review_length"
)[[
    "Company",
    "rating",
    "review_text"
]]

       Company  rating                                        review_text
753   HomeLane       1  BEST EXPERIENCE TILL YOU PAY MONEY, WORST AS S...
365   Livspace       1  A cautionary account for anyone considering Li...
674   HomeLane       1  I recently availed the interior renovation ser...
511   Livspace       1  We are extremely disappointed with our experie...
317   Livspace       1  "Livpace: Where Deadlines Go to Die"\n Hired L...
403   Livspace       1  Experience is very worst due to fake and false...
698   HomeLane       1  I paid â¹25,000 to HomeLane for interior desi...
707   HomeLane       1  I booked interior services with homelane aroun...
0    Minimalix       1  I had a very disappointing experience with Min...
458   Livspace       1  Stay away from livspace\n Livspace done third ...

| Company   | Main Pain Point                 |
| --------- | ------------------------------- |
| Minimalix | Lead Quality & Subscription ROI |
| HomeLane  | Delays & Project Execution      |
| Livspace  | Post-Sales Service & Value Gap  |

## TF-IDF Insights

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=100
)

X = tfidf.fit_transform(
    negative_df["processed_text"]
)

words = tfidf.get_feature_names_out()

scores = X.sum(axis=0).A1

tfidf_df = pd.DataFrame({
    "word": words,
    "score": scores
}).sort_values(
    "score",
    ascending=False
)

tfidf_df.head(30)

              word     score
15         company  7.926406
47            lead  5.968215
41        homelane  5.727799
82         service  5.683872
4              bad  5.469256
98            work  5.462853
55           money  5.412510
32      experience  5.314633
70         project  5.148554
85            team  5.104193
27             don  4.154945
89            time  3.874236
36           fraud  3.853151
23          design  3.700044
72         provide  3.248311
61             pay  3.119414
16        complete  3.034546
92  unprofessional  3.010198
19        customer  2.990784
37            good  2.980684
38             hai  2.960123
56           month  2.951912
65            poor  2.810500
96           waste  2.782348
48            like  2.729119
74       recommend  2.668349
54       minimalix  2.619696
43        interior  2.595361
71         promise  2.478600
79          review  2.427747

999 Reviews
3 Companies
546 Text Reviews
453 Rating-only Reviews

## ***Customers care more about experience than design.***

| Root Cause               | Keywords                   | Business Impact          |
| ------------------------ | -------------------------- | ------------------------ |
| Service Quality          | service, support, response | Customer dissatisfaction |
| Value for Money          | money, pay, waste          | Lower trust & referrals  |
| Delivery Delays          | month, time                | Poor customer experience |
| Expectation Gap          | promise, provide           | Trust erosion            |
| Professionalism          | unprofessional, fraud      | Brand damage             |
| Lead Quality (Minimalix) | lead                       | Partner dissatisfaction  |

## Topic Modeling (BERTopic)

In [ ]:
!pip install bertopic
!pip install sentence-transformers
!pip install umap-learn

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.44)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.5.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.25.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 5.0 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.4
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Requirement already satisfied: umap-learn in /usr/local/lib/python3.12/dist-packages (0.5.12)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (2.0.2)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (1.16.3)
Requirement already satisfied: scikit-learn>=1.6 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (1.6.1)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.6.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from umap-learn) (4.67.3)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.2->umap-learn) (0.43.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from pynndescent>=0.5->umap-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6->umap-learn) (3.6.0)

In [ ]:
from bertopic import BERTopic

topic_model = BERTopic(
    min_topic_size=10,
    verbose=True
)

topics, probs = topic_model.fit_transform(
    text_df["processed_text"]
)

2026-06-18 14:03:57,326 - BERTopic - Embedding - Transforming documents to embeddings.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/18 [00:00<?, ?it/s]

2026-06-18 14:04:15,472 - BERTopic - Embedding - Completed ✓
2026-06-18 14:04:15,476 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-06-18 14:04:31,986 - BERTopic - Dimensionality - Completed ✓
2026-06-18 14:04:31,989 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-06-18 14:04:32,022 - BERTopic - Cluster - Completed ✓
2026-06-18 14:04:32,031 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-06-18 14:04:32,072 - BERTopic - Representation - Completed ✓

In [ ]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,15,-1_ansar_job_good_work,"[ansar, job, good, work, gangsara, akhilesh, a...","[ansar, ansar complete job, ansar good job]"
1,0,244,0_homelane_design_work_team,"[homelane, design, work, team, experience, pro...",[recently avail interior renovation service ho...
2,1,221,1_minimalix_lead_service_customer,"[minimalix, lead, service, customer, good, sup...","[good company excellent customer service, mini..."
3,2,18,2_company_good_nice_job,"[company, good, nice, job, bad, vicky, work, o...","[good company, good company, good company]"
4,3,18,3_painter_job_shahjahan_good,"[painter, job, shahjahan, good, shah, jahan, s...","[shah jahan painter excellent job, shahjahan p..."
5,4,17,4_good_nice_love_excellent,"[good, nice, love, excellent, , , , , , ]","[good, good, good]"
6,5,13,5_post_sale_saroj_service,"[post, sale, saroj, service, sunil, sales, wor...","[post sale service saroj sunil good, post sale..."

In [ ]:
topic_model.get_topic(0)
topic_model.get_topic(1)
topic_model.get_topic(2)

[('company', np.float64(0.7199609157061417)),
 ('good', np.float64(0.5320525668853199)),
 ('nice', np.float64(0.18818251131543376)),
 ('job', np.float64(0.17842575972236613)),
 ('bad', np.float64(0.17842575972236613)),
 ('vicky', np.float64(0.16035500005892148)),
 ('work', np.float64(0.15237052210558433)),
 ('office', np.float64(0.14496805124776693)),
 ('satisfy', np.float64(0.14496805124776693)),
 ('satisfactory', np.float64(0.13597402540063164))]

| Theme ID | Business Theme                           | Count |
| -------- | ---------------------------------------- | ----- |
| 0        | Home Interior Design & Project Execution | 236   |
| 1        | Customer Support & Service Quality       | 99    |
| 2        | Professional Design Experience           | 53    |
| 4        | Lead Quality & Lead Management           | 26    |
| 7        | Subscription Plans & PLP Programs        | 13    |
| 8        | Post-Sales Support Experience            | 13    |
| 9        | Refund, Fraud & Trust Issues             | 11    |

In [ ]:
text_df["topic"] = topics

In [ ]:
text_df[["Company","rating","topic"]].head()

     Company  rating  topic
0  Minimalix       1      1
1  Minimalix       5      1
2  Minimalix       5      1
3  Minimalix       5      1
4  Minimalix       1      1

In [ ]:
pd.crosstab(
    text_df["Company"],
    text_df["topic"]
)

topic      -1    0    1   2   3   4   5
Company
HomeLane    4  174   31   2   0   6   0
Livspace    9   55   22   4  18   8  13
Minimalix   2   15  168  12   0   3   0

Customers rarely complain about aesthetics alone. Most dissatisfaction originates from service delivery, communication, timelines, support quality, and perceived value.

Sentiment Score + Label

In [ ]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.5.20)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 3.6 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

text_df["sentiment_score"] = text_df["review_text"].apply(
    lambda x: analyzer.polarity_scores(str(x))["compound"]
)

def get_sentiment_label(score):
    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    return "Neutral"

text_df["sentiment_label"] = text_df["sentiment_score"].apply(
    get_sentiment_label
)

In [ ]:
pd.crosstab(
    text_df["Company"],
    text_df["sentiment_label"],
    normalize="index"
).round(3) * 100

sentiment_label  Negative  Neutral  Positive
Company
HomeLane             14.7      6.0      79.3
Livspace             14.7     12.4      72.9
Minimalix            11.5      7.5      81.0

In [ ]:
topic_map = {
    0:"Design & Project Experience",
    1:"Customer Service & Support",
    2:"Interior Design Professionals",
    3:"Company Reputation",
    4:"Lead Quality",
    5:"General Appreciation",
    6:"Painter Workforce",
    7:"PLP Subscription",
    8:"Post Sales Support",
    9:"Fraud & Refund Concerns"
}

text_df["topic_name"] = text_df["topic"].map(topic_map)

In [ ]:
final_df = text_df[
[
    "Company",
    "rating",
    "reviewer",
    "review_text",
    "review_length",
    "segment",
    "sentiment_score",
    "sentiment_label",
    "topic",
    "topic_name",
    "processed_text"
]]

In [ ]:
final_df = text_df.copy()

final_df.to_csv(
    "voc_analytics_final.csv",
    index=False
)

In [ ]:
final_df.head(5)

,Company,rating,reviewer,review_text,review_length,clean_text,processed_text,segment,topic,sentiment_score,sentiment_label,topic_name
0,Minimalix,1,Hardik Ojha,I had a very disappointing experience with Min...,1054,i had a very disappointing experience with min...,disappointing experience minimalics official j...,Partner,1,-0.9203,Negative,Customer Service & Support
1,Minimalix,5,Vipin Pal,"Recently I subscribed PLP Pro Plus, out of 6 l...",129,recently i subscribed plp pro plus out of lead...,recently subscribe plp pro plus lead visit con...,Partner,1,0.4404,Positive,Customer Service & Support
2,Minimalix,5,Johnsan Barla,As per my overall experience Minimalix is one ...,123,as per my overall experience minimalix is one ...,overall experience minimalix good company term...,General,1,0.7902,Positive,Customer Service & Support
3,Minimalix,5,The Design Studiokl,1/5\n \n My experience with Minimalix has been...,1576,my experience with minimalix has been extremel...,experience minimalix extremely disappointing s...,Partner,1,0.5740,Positive,Customer Service & Support
4,Minimalix,1,Supriya Vimal,"Very BadMost of the leads were either invalid,...",253,very badmost of the leads were either invalid ...,badmost lead invalid badinterested enquiry fee...,Partner,1,-0.4596,Negative,Customer Service & Support

In [ ]:
files.download('voc_analytics_final.csv')

## Conclusion

The analysis shows that customer dissatisfaction is driven more by operational and service-related issues than design quality.

Across competitors:

- HomeLane struggles with execution and delivery timelines.
- Livspace faces post-sales service challenges.
- Minimalix faces lead quality and subscription ROI concerns.

Improving communication, service consistency, and lead qualification processes can significantly improve customer satisfaction and retention.